# _config.yml
title: DeriqAI Releases
description: DeriqAI releases
baseurl: "/releases"
url: "https://deriqai.github.io"

# Theme settings
# Use the jekyll-remote-theme plugin to use a GitHub theme
plugins:
  - jekyll-remote-theme

remote_theme: pages-themes/primer@latest